### ISSUE TITLE
Not lexing assignment to unary op

### ISSUE THREAD

**Issue by DariusL** [SusirinkeLaborams/LaborasLang-aka-ForScience-#21]
++a = 8;
++a is an lvalue, should be valid.

**Comment by AndriusDap** [comment]
``` ++a = 8; ``` is not valid, it does not make any sense.
But ```foo().bar = 5;``` should be valid

**Comment by DariusL** [comment]
The parser will support both because it would be difficult to *not* support it, so `++a = foo` can be failed while lexing.

**Comment by AndriusDap** [comment]
solved
