### ISSUE TITLE
Array of functor don't work

### ISSUE THREAD

**Issue by DariusL** [SusirinkeLaborams/LaborasLang-aka-ForScience-#40]
.Resolve() on an array of functors throws NotSupportedOperation

eg int()[]

**Comment by Sunius** [comment]
By design. Array is a type specification, not a type definition - therefore there is nothing to resolve.

**Comment by DariusL** [comment]
It crashes inside your code when defining an array of functors
debug TestFunctorArrayType in 6c507626f81de68be8a5607334fd9d8a841a2101

**Comment by DariusL** [comment]
Closed by 3e176a875d6996d6626043dfb4d29936d8087825
